server:
  port: 8082
spring:
  datasource:
   dynamic:
     primary: master
     datasource:
       master:
         username: cln_db
         password: Cln2020!
         driver-class-name: com.mysql.cj.jdbc.Driver
         url:  jdbc:mysql://10.20.204.130:3306/g_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
       coloan:
         username: coloan_phase3
         password: coloan_phase3
         driver-class-name: oracle.jdbc.driver.OracleDriver
         url: jdbc:oracle:thin:@10.20.201.173:1521:rtl15ddb
mybatis-plus:
  type-aliases-package: com.jzjr.mybatisoperating.entity
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#通用mapper
  #主键自增回写
mapper:
  identity: mysql
  mappers: tk.mybatis.mapper.common.BaseMapper
  #设置以后，会去判断 insert 和 update 中符串类型!=''
  not-empty: true
  #枚举按简单类型处理，如果有枚举字段则需要加上该配置才会做映射
  enum-as-simple-type: true
#分页插件
pagehelper:
  auto-dialect: mysql #指定分页插件使用的语言，也可以不写，会根据数据源来使用数据库
  params: count = countSql
  ##分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: false
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true

logging:
  level:
    com.jzjr.mybatisoperating.mapper: debug
